// File: components/footer/schema.ts
export const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Hospital",
  name: "CMI Hospital",
  alternateName: "Canon Medicinae Indonesia Hospital",
  description:
    "Rumah sakit yang memberikan pelayanan kesehatan dengan menggabungkan Ilmu Kedokteran Barat (Konvensional Modern) dengan Ilmu Kedokteran Klasik berdasarkan buku The Canon of Medicine (Al Qanun fii At-Tibb) karya dr. Ibnu Sina secara terintegrasi.",
  url: "https://cmihospital.com",
  logo: "https://cmihospital.com/assets/images/logo.svg",
  image: "https://cmihospital.com/assets/images/hospital-exterior.jpg",
  telephone: "+62821-2159-0000",
  email: "info@cmihospital.com",
  address: {
    "@type": "PostalAddress",
    streetAddress: "Jl. Tubagus Ismail VII, Sekeloa",
    addressLocality: "Kecamatan Coblong",
    addressRegion: "Kota Bandung, Jawa Barat",
    postalCode: "40134",
    addressCountry: "ID",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: "-6.8951",
    longitude: "107.6084",
  },
  openingHours: ["Mo-Sa 08:00-17:00"],
  specialOpeningHoursSpecification: {
    "@type": "OpeningHoursSpecification",
    dayOfWeek: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    opens: "00:00",
    closes: "23:59",
    validFrom: "2024-01-01",
    description: "Emergency Department - 24 Hours",
  },
  sameAs: [
    "https://facebook.com/cmihospital",
    "https://instagram.com/cmihospital",
    "https://twitter.com/cmihospital",
    "https://linkedin.com/company/cmihospital",
    "https://youtube.com/@cmihospital",
  ],
  medicalSpecialty: [
    "Oncology",
    "Cardiology",
    "Endocrinology",
    "Nephrology",
    "Preventive Medicine",
    "Laboratory Medicine",
  ],
};
